name: Gitea Actions Demo
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀
on: [push]



jobs:
  # Build job
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ gitea.event_name }} event."
      - run: echo "The name of your branch is ${{ gitea.ref }} and your repository is ${{ gitea.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: 'true'
          github-server-url: 'https://lab.cynic.club'
      #- name: Install apt packages
      #  run: apt update && apt install -y jq rsync
      - name: Get latest Hugo version
        run: |
          url=$(curl --silent "https://api.github.com/repos/gohugoio/hugo/releases/latest" | jq -r '.assets[] | select(.name | contains("linux-amd64.tar.gz")) | .browser_download_url' | grep -E 'hugo_[0-9]+\.[0-9]+\.[0-9]+_linux-amd64.tar.gz')
          wget -P /tmp/hugo/ "$url"
          version=$(echo "$url" | grep -oP 'hugo_\K[0-9]+\.[0-9]+\.[0-9]+')
          echo "Downloaded Hugo version: $version"
      - name: Unpack Hugo
        run: tar -xf /tmp/hugo/* -C ${{ gitea.workspace }}/bin



      - name: Build the static webpage
        run: ${{ gitea.workspace }}/bin/hugo --minify --cleanDestinationDir 

      - name: Build the static webpage (docker)
        uses: docker://hugomods/hugo
        run: hugo --minify --cleanDestinationDir 
      
      - name: rsync deployments
        uses: burnett01/rsync-deployments@4.1
        with:
          # -v: verbose
          # -z: compress files during transfer
          # -r: copy files recursively
          # --delete: delete extraneous files from dest dirs
          switches: -avzhe --delete
          path: /public/
          remote_path: /www/wwwroot/new.blohina.com.ua
          remote_host: 192.168.50.105
          remote_user: root
          remote_key: ${{ secrets.AAPANEL_SSH_KEYS }}  