name: Gitea Actions Demo
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀
on: [push]



jobs:
  # Build job
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ gitea.event_name }} event."
      - run: echo "The name of your branch is ${{ gitea.ref }} and your repository is ${{ gitea.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: 'true'
          github-server-url: 'https://lab.cynic.club'
      - name: Install apt packages
        run: apt update && apt install -y jq rsync
      - name: Get latest Hugo version
        run: |
          url=$(curl --silent "https://api.github.com/repos/gohugoio/hugo/releases/latest" | jq -r '.assets[] | select(.name | contains("linux-amd64.tar.gz")) | .browser_download_url' | grep -E 'hugo_[0-9]+\.[0-9]+\.[0-9]+_linux-amd64.tar.gz')
          wget -P /tmp/hugo/ "$url"
          version=$(echo "$url" | grep -oP 'hugo_\K[0-9]+\.[0-9]+\.[0-9]+')
          echo "Downloaded Hugo version: $version"
      - name: Unpack Hugo
        run: tar -xf /tmp/hugo/* -C ${{ gitea.workspace }}/bin

      - name: Add SSH key
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p /home/runner/.ssh
                  # Replace example.com with the hostname of the machine
                  # you're SSH-ing into
          ssh-keyscan example.com >> /home/runner/.ssh/known_hosts
                  # DOKKU_SSH_KEY is the name of the repository secret
          echo "${{ secrets.DOKKU_SSH_KEYS }}" > /home/runner/.ssh/github_actions
          chmod 600 /home/runner/.ssh/github_actions
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null	
          ssh-add /home/runner/.ssh/github_actions
      - name: Build the static webpage
        run: ${{ gitea.workspace }}/bin/hugo --minify --cleanDestinationDir && rsync -avzhe ssh ${{ gitea.workspace }}/public/ root@192.168.50.105:/www/wwwroot/new.blohina.com.ua --delete